version: "3.9"
services:
  user-db:
    container_name: case-db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: case_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - law-case-db-data:/var/lib/postgresql/data
volumes:
  law-case-db-data: